### ISSUE TITLE
Mise à jour 10.0.6 en echec

### ISSUE THREAD

**Issue by MacMatt** [YunoHost-Apps/glpi_ynh#14]
Bonjour

J'ai essayé de mettre à jour de 10.0.5 en 10.0.6, mais cela se termine malheureusement en échec.

Historique :
Installation de la 10.0.5 directement sur un YNH fraichement installé.

Installation en manuel de
> apt-get install php7.4-bz2
> apt-get install php7.4-zip
_(nécessaire et non installé par YNH, ni lorsqu'on installe l'application GLPI via YNH)_

Augmentation de la taille maximal des upload pour Nginx
> /etc/nginx/conf.d/glpi.cnd.fr.d/glpi.conf

Aucune autre modification particulière a priori

J'ai donc utilisé la fonction de mise à jour de YNH pour updater mais échec avec les logs suivants :

https://paste.yunohost.org/raw/lurediyane

En espérant que vous trouviez ce qui ne fonctionne pas et comment le solutionner :-)

Bon courage

Matthieu

**Comment by manubg17** [comment]
Bonjour,

J'ai aussi eu des erreurs en tentant de mettre à jour GLPI de 10.0.5 à 10.0.6.

J'ai installé les paquets php8.0-cli et php8.0-xmlrpc via apt install et ensuite mis à jour GLPI, cela a fonctionner pour moi.

Il restera ensuite a effacé le dossier install/install.php à la main.

En espérant que cela puisse aider, je vous souhaite une bonne journée

Manu

**Comment by MacMatt** [comment]
Bonjour

Merci pour cette information utile

Me concernant je n'ai eu qu'à installer apt-get install php8.0-xmlrpc car le php8.0-cli était déjà en place.
Ensuite, ma mise à jour s'est effectivement effectuée correctement 

Matthieu

**Comment by Salamandar** [comment]
Should be fixed now.
