### ISSUE TITLE
Update 10.0.6 -> 10.0.10 fails

### ISSUE THREAD

**Issue by dbflexi** [YunoHost-Apps/glpi_ynh#23]
### Describe the bug

Update from 10.0.6-ynh1 to 10.0.10-ynh1 fails

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.5
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: glpi 10.0.10
- If upgrading, current package version: *10.0.6*

### Steps to reproduce

1. Login to Webadmin
2. search for Updates
3. click on update at GLPI

also tried to update from CLI, with and without -c

### Expected behavior

*Update to newest version*

### Logs

https://paste.yunohost.org/raw/ibapohilol

**Comment by clicit** [comment]
Exactly the same problem here!

https://paste.yunohost.org/raw/ubutiwoxes

**Comment by Salamandar** [comment]
Yep, that's fixed, sorry for the issue.
